[book]
authors = ["scyfar"]
description = "Scydvendure - An opinionated modpack"
language = "en"
multilingual = false
src = "src"
title = "Scydventure â›ğŸ›¡ğŸª„"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/scyfar/scydventure"

[preprocessor.alerts]
